# Generated by Django 4.2.4 on 2023-10-16 06:50

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_title', models.CharField(max_length=100)),
                ('course_price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('course_des', tinymce.models.HTMLField()),
                ('course_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advance', 'Advance')], default='Beginner', max_length=50)),
                ('course_duration', models.CharField(max_length=100)),
                ('course_image', models.ImageField(default='course/courses-1.jpg', null=True, upload_to='corse/')),
                ('course_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='course_title', unique=True)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
