# Generated by Django 4.2.4 on 2023-10-16 09:49

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='review',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='skills',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_des',
            field=tinymce.models.HTMLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_duration',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
