# Generated by Django 4.2.4 on 2023-10-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
        ('course', '0002_courses_review_courses_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='skills_req',
            field=models.ManyToManyField(to='uploads.skil'),
        ),
    ]
