# Generated by Django 4.2.4 on 2023-10-16 12:58

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship')], default=None, max_length=50, null=True)),
                ('exp_required', models.CharField(max_length=100)),
                ('job_des', tinymce.models.HTMLField(blank=True, null=True)),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Enter the minimum salary for this job (e.g., 50000.00)', max_digits=10, null=True, verbose_name='Minimum Salary')),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Enter the maximum salary for this job (e.g., 80000.00)', max_digits=10, null=True, verbose_name='Maximum Salary')),
                ('company', models.CharField(default=None, max_length=100)),
                ('location', models.CharField(max_length=250)),
                ('company_desc', tinymce.models.HTMLField(blank=True, null=True)),
                ('url', models.URLField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('job_image', models.ImageField(default='job/jobs-1.jpg', upload_to='job/')),
                ('job_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='get_full_slug', unique=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_closed', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.category')),
                ('skills_req', models.ManyToManyField(to='uploads.skil')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.job')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
