# Generated by Django 4.2.4 on 2023-10-16 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='skil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_image', models.ImageField(default='profile/profile-default.jpg', null=True, upload_to='profile/')),
                ('profile_desc', models.TextField(blank=True, max_length=250)),
                ('institution', models.CharField(blank=True, max_length=50)),
                ('resume', models.FileField(default='resume/resume.pdf', null=True, upload_to='resume/')),
                ('resume_data', models.TextField(default='RESUME', max_length=3000, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='IN', unique=True)),
                ('gender', models.CharField(max_length=100)),
                ('work_at', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('is_job', models.BooleanField(default=False)),
                ('is_course', models.BooleanField(default=False)),
                ('position', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uploads.industry')),
                ('skills', models.ManyToManyField(to='uploads.skil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
